---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-vault-agent-config
data:
  template.ctmpl: |
    {{- with secret "secret/data/hello/config" -}}
      username: {{ .Data.data.username }}, password: {{ .Data.data.password }}
    {{- end -}}
  config-init.hcl: |
    exit_after_auth = true

    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            config = {
                role = "hello"
            }
        }

        sink "file" {
            config = {
                path = "/vault/secrets/token"
                mode = 0644
            }
        }
    }

    template {
        destination = "/vault/secrets/config.txt"
        source = "/vault/configs/template.ctmpl"
    }
  config.hcl: |
    exit_after_auth = false

    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            config = {
                role = "hello"
            }
        }

        sink "file" {
            config = {
                path = "/vault/secrets/token"
                mode = 0644
            }
        }
    }

    template {
        destination = "/vault/secrets/config.txt"
        source = "/vault/configs/template.ctmpl"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'hello'
        vault.hashicorp.com/agent-configmap: 'hello-vault-agent-config'
    spec:
      serviceAccountName: internal-app
      containers:
        - name: hello
          image: ko://github.com/bradbeck/ko-vault/cmd
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ADDR
              value: http://external-vault:8200
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8080
